MyGroupVesionsでres['my_group_item']がnullのときは空配列を返すようにする
miyajan/garoon-soap pull request #2
Opened 2020-01-19 22:41 UTC by kuroppe1819

タイトルの通りです。

2020-01-20 13:12 UTC, miyajan requested changes

2020-01-20 13:12 UTC, miyajan commented on src/client/base.ts
> +            if (myGroupItem == null) {
```suggestion
            if (myGroupItem === undefined) {
```
あまり `==` 使いたくないので、こんな感じでお願いします！

2020-01-23 03:01 UTC, miyajan commented
@kuroppe1819 レビュー対応お願いします！

2020-02-01 07:41 UTC, kuroppe1819 commented
修正しました〜！

2020-02-01 07:44 UTC, miyajan approved these changes

2020-02-01 07:44 UTC, merged